# Generated by Django 4.2.7 on 2023-11-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=25)),
                ('desc', models.TextField(max_length=300)),
                ('address', models.TextField(max_length=150)),
                ('model', models.CharField(choices=[('BUNGALOW', 'Bungalow'), ('DUPLEX', 'Duplex'), ('SELFCONTAIN', 'Selfcontain')], max_length=30)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_agent', to='agent.agent')),
            ],
        ),
    ]
