# Generated by Django 4.2.7 on 2023-11-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='goal',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('shortlet', 'Shortlet')], default='rent', max_length=10),
            preserve_default=False,
        ),
    ]
